app = 'rollount-manager-backend'
primary_region = 'gru'

[processes]
  app= 'bash -c "chmod +x /app/entrypoint.sh && /app/entrypoint.sh"'

[build]
  dockerfile = 'Dockerfile'

[deploy]
  strategy = 'rolling'
  max_unavailable = 1

[env]
  NODE_ENV = 'production'
  PORT = '3344'

[http_service]
  internal_port = 3344
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 500

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1